name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # 필요한 Node.js 버전을 설정하세요.

      - name: Install dependencies
        working-directory: ./fe # fe 디렉토리로 변경
        run: npm install

      - name: Build
        working-directory: ./fe # fe 디렉토리로 변경
        run: npm run build

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #   필요한 다른 설정 및 백엔드 작업 수행
      #   예: Python, Java, 또는 다른 언어를 사용할 경우 관련 설정 추가
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./be
        run: |
          pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
